
class UserNotFound(Exception):
    """Common base class for not found users""" 
    
class UserNotFoundInDatabase(UserNotFound): ...
class UserNotFoundInChat(UserNotFound): ...
class UserNotFoundInMessage(UserNotFound): ...
