"""create initial schema

Revision ID: e8483e5941fe
Revises:
Create Date: 2026-09-06 12:11:38.491102

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8483e5941fe"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("rules", sa.String(), nullable=True),
        sa.Column("welcome_message", sa.String(), nullable=True),
        sa.Column("goodbye_message", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("creator_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_table(
        "cooldowns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ghouls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("rc_money", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("snap_count", sa.Integer(), nullable=False),
        sa.Column("kagune_type_bit", sa.Integer(), nullable=True),
        sa.Column("kagune_strength", sa.Integer(), nullable=False),
        sa.Column("strength", sa.Integer(), nullable=False),
        sa.Column("dexterity", sa.Integer(), nullable=False),
        sa.Column("speed", sa.Integer(), nullable=False),
        sa.Column("health", sa.Integer(), nullable=False),
        sa.Column("max_health", sa.Integer(), nullable=False),
        sa.Column("regeneration", sa.Integer(), nullable=False),
        sa.Column("eat_humans", sa.Integer(), nullable=False),
        sa.Column("eat_ghouls", sa.Integer(), nullable=False),
        sa.Column("is_kakuja", sa.Boolean(), nullable=False),
        sa.Column("coffee_count", sa.Integer(), nullable=False),
        sa.Column("hunger", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_table(
        "media",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("media_type", sa.String(), nullable=False),
        sa.Column("telegram_file_id", sa.String(), nullable=True),
        sa.Column("collection", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("uploaded_by", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rp_commands",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("command", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column(
            "type_command",
            sa.Enum("TEXT", "PHOTO", "ANIMATION", name="typerpcommandenum"),
            nullable=False,
        ),
        sa.Column("file_id", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "command", name="unique_chat_command"),
    )
    op.create_index(
        op.f("ix_rp_commands_chat_id"), "rp_commands", ["chat_id"], unique=False
    )
    op.create_index(
        op.f("ix_rp_commands_command"), "rp_commands", ["command"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("race_bit", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Integer(), nullable=False),
        sa.Column("energy", sa.Integer(), nullable=False),
        sa.Column("energy_consumption", sa.Integer(), nullable=False),
        sa.Column("happyness", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("ban_reason", sa.String(), nullable=True),
        sa.Column("banned_until", sa.DateTime(), nullable=True),
        sa.Column("has_private_chat", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "lotteries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("bet_amount", sa.Integer(), nullable=False),
        sa.Column("chosen_color", sa.String(), nullable=False),
        sa.Column("winning_color", sa.String(), nullable=False),
        sa.Column("is_won", sa.Boolean(), nullable=False),
        sa.Column("earned", sa.Integer(), nullable=False),
        sa.Column("video_file_id", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["telegram_id"], ["users.telegram_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users_cooldowns",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("cooldown_id", sa.Integer(), nullable=False),
        sa.Column("end_at", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["cooldown_id"], ["cooldowns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "cooldown_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_cooldowns")
    op.drop_table("lotteries")
    op.drop_table("users")
    op.drop_index(op.f("ix_rp_commands_command"), table_name="rp_commands")
    op.drop_index(op.f("ix_rp_commands_chat_id"), table_name="rp_commands")
    op.drop_table("rp_commands")
    op.drop_table("media")
    op.drop_table("ghouls")
    op.drop_table("cooldowns")
    op.drop_table("chats")
    # ### end Alembic commands ###
